######################################################################
# Automatically generated by qmake (3.0) pt. mar 13 10:43:19 2015
######################################################################

QT += testlib
CONFIG += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += CPathFinderTest.h
SOURCES += CPathFinderTest.cpp
