name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            configure: ./configure.sh
            artifact: cmake-build-release/fall-of-nouraajd-*.tar.gz
          - os: windows-latest
            configure: ./configure.bat
            artifact: cmake-build-release/fall-of-nouraajd-*.exe
    steps:
      - uses: actions/checkout@v3
      - name: submodules
        run: git submodule update --init --recursive
      - name: configure
        run: ${{ matrix.configure }}
      - name: make
        run: make -C cmake-build-release package
      - name: publish
        uses: actions/upload-artifact@v4
        with:
          name: fall-of-nouraajd
          path: ${{ matrix.artifact }}
