name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: submodules
        run: git submodule update --init --recursive
      - name: configure
        run: ./configure.sh
      - name: make
        run: make -C cmake-build-release package
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: cmake-build-release/fall-of-nouraajd-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
