name: ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule init
    - name: configure
      run: ./configure.sh
    - name: make
      run: make -C cmake-build-release package
    - name: publish
      uses: actions/upload-artifact@v2
      with:
        name: fall-of-nouraajd
        path: fall-of-nouraajd-0.1.1-.tar.gz
    
