name: windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init --recursive
    - name: configure
      run: ./configure.bat
    - name: make
      run: make -C cmake-build-release package
    - name: publish
      uses: actions/upload-artifact@v2
      with:
        name: fall-of-nouraajd
        path: cmake-build-release/fall-of-nouraajd-*.tar.gz
